### ISSUE TITLE
It doesn't run well, as you say .

### ISSUE THREAD

**Issue by 61go** [Polygon-Academy/Tutorial-nft-marketplace#3]
@localhost Tutorial-nft-marketplace-main % truffle migrate --network development --reset 

Compiling your contracts...
===========================
⠏ Fetching solc version list from solc-bin. Attempt #1
/Users/***//Downloads/Tutorial-nft-marketplace-main/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:57
          const err = new Error(msg)
                      ^
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: Unknown Error: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
</body>
</html>

    at Request._callback (/Users/***/Downloads/Tutorial-nft-marketplace-main/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:57:23)
    at Request.self.callback (/Users/***/Downloads/Tutorial-nft-marketplace-main/node_modules/request/request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.<anonymous> (/Users/***//Downloads/Tutorial-nft-marketplace-main/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:394:28)
    at IncomingMessage.<anonymous> (/Users/***//Downloads/Tutorial-nft-marketplace-main/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1329:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at PollingBlockTracker._performSync (/Users/***//Downloads/Tutorial-nft-marketplace-main/node_modules/eth-block-tracker/src/polling.js:51:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by BrianSeong99** [comment]
seems to me that your truffle struggles to connect to the rpc, maybe check your network config or your rpc connection
